-- Source Database Initialization Script
-- This database will contain source accounts for transfers

USE bank_source;

-- Account table
CREATE TABLE IF NOT EXISTS rb_acct (
    INTERNAL_KEY BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENT_NO VARCHAR(20) NOT NULL,
    BASE_ACCT_NO VARCHAR(50) NOT NULL UNIQUE,
    ACCT_NAME VARCHAR(200),
    ACCT_CCY VARCHAR(3) DEFAULT 'CNY',
    ACCT_STATUS CHAR(1) DEFAULT 'A',
    ACCT_BRANCH VARCHAR(20),
    ACCT_OPEN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TRAN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_base_acct_no (BASE_ACCT_NO),
    INDEX idx_client_no (CLIENT_NO),
    INDEX idx_acct_status (ACCT_STATUS)
);

-- Account Balance table
CREATE TABLE IF NOT EXISTS rb_acct_balance (
    INTERNAL_KEY BIGINT PRIMARY KEY,
    CLIENT_NO VARCHAR(20) NOT NULL,
    TOTAL_AMOUNT DECIMAL(20,2) DEFAULT 0.00,
    LAST_CHANGE_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TRAN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (INTERNAL_KEY) REFERENCES rb_acct(INTERNAL_KEY),
    INDEX idx_client_no (CLIENT_NO)
);

-- Transaction History table
CREATE TABLE IF NOT EXISTS rb_tran_hist (
    SEQ_NO VARCHAR(50) PRIMARY KEY,
    INTERNAL_KEY BIGINT,
    CLIENT_NO VARCHAR(20),
    BASE_ACCT_NO VARCHAR(50),
    TRAN_TYPE VARCHAR(10),
    TRAN_AMT DECIMAL(20,2),
    PREVIOUS_BAL_AMT DECIMAL(20,2),
    ACTUAL_BAL DECIMAL(20,2),
    CR_DR_IND CHAR(1),
    TRAN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    REFERENCE VARCHAR(50),
    NARRATIVE VARCHAR(500),
    TRAN_STATUS CHAR(1) DEFAULT 'N',
    TRAN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_internal_key (INTERNAL_KEY),
    INDEX idx_reference (REFERENCE),
    INDEX idx_tran_date (TRAN_DATE),
    INDEX idx_base_acct_no (BASE_ACCT_NO)
);

-- Transfer Log table (shared across both databases)
CREATE TABLE IF NOT EXISTS transfer_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    transfer_id VARCHAR(50) UNIQUE NOT NULL,
    from_account VARCHAR(50) NOT NULL,
    to_account VARCHAR(50) NOT NULL,
    amount DECIMAL(20,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'CNY',
    status ENUM('PENDING', 'SUCCESS', 'FAILED', 'ROLLBACK') DEFAULT 'PENDING',
    error_message TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_transfer_id (transfer_id),
    INDEX idx_status (status),
    INDEX idx_created_at (created_at),
    INDEX idx_from_account (from_account)
);

-- Insert sample source accounts
INSERT INTO rb_acct (CLIENT_NO, BASE_ACCT_NO, ACCT_NAME, ACCT_CCY, ACCT_STATUS, ACCT_BRANCH) VALUES
('1108803572', '6230399991006371427', '张三', 'CNY', 'A', '0503'),
('1108803573', '6230399991006371428', '李四', 'CNY', 'A', '0503'),
('1108803574', '6230399991006371429', '王五', 'CNY', 'A', '0503');

-- Insert corresponding balances
INSERT INTO rb_acct_balance (INTERNAL_KEY, CLIENT_NO, TOTAL_AMOUNT) VALUES
(1, '1108803572', 10000.00),
(2, '1108803573', 15000.00),
(3, '1108803574', 8000.00);

-- Account restrictions table
CREATE TABLE IF NOT EXISTS rb_restraints (
    INTERNAL_KEY BIGINT,
    RESTRAINT_TYPE VARCHAR(10),
    RES_SEQ_NO VARCHAR(20),
    CLIENT_NO VARCHAR(20),
    REAL_RESTRAINT_AMT DECIMAL(20,2) DEFAULT 0.00,
    RESTRAINTS_STATUS CHAR(1) DEFAULT 'A',
    TRAN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (INTERNAL_KEY, RES_SEQ_NO),
    INDEX idx_client_no (CLIENT_NO),
    INDEX idx_restraint_type (RESTRAINT_TYPE)
);

-- Client transaction limits table
CREATE TABLE IF NOT EXISTS rb_lm_client_tran_limit (
    BASE_ACCT_NO VARCHAR(50),
    ACCT_CCY VARCHAR(3),
    CLIENT_NO VARCHAR(20),
    LIMIT_REF VARCHAR(50),
    LIMIT_MAX_AMT DECIMAL(20,2),
    LIMIT_MIN_AMT DECIMAL(20,2),
    TRAN_DATE DATE,
    TRAN_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BASE_ACCT_NO, LIMIT_REF),
    INDEX idx_client_no (CLIENT_NO)
);

-- Insert default transaction limits
INSERT INTO rb_lm_client_tran_limit (BASE_ACCT_NO, ACCT_CCY, CLIENT_NO, LIMIT_REF, LIMIT_MAX_AMT, LIMIT_MIN_AMT, TRAN_DATE) VALUES
('6230399991006371427', 'CNY', '1108803572', 'DailyTransferLimit', 50000.00, 0.01, CURDATE()),
('6230399991006371428', 'CNY', '1108803573', 'DailyTransferLimit', 50000.00, 0.01, CURDATE()),
('6230399991006371429', 'CNY', '1108803574', 'DailyTransferLimit', 50000.00, 0.01, CURDATE());